CREATE TYPE "government" AS ENUM (
 'DESPOTISM',
 'DIARCHY',
 'TECHNOCRACY'
);
CREATE TYPE "standardOfLiving" AS ENUM (
 'ULTRA_HIGH',
 'HIGH',
 'VERY_LOW'
);
CREATE TABLE IF NOT EXISTS "Human" (
 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "age" bigint NOT NULL,
 "height" bigint NOT NULL,
 "birthday" date
);
CREATE TABLE IF NOT EXISTS "Users" (
 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" varchar(100) UNIQUE,
 "hash" bytea NOT NULL,
 "salt" varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS "Coordinates" (
 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "x" double precision NOT NULL,
 "y" double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS "City" (
 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" varchar NOT NULL,
 "owner_id" int NOT NULL,
 "coordinates_id" int NOT NULL,
 "creation_date" date NOT NULL,
 "area" float NOT NULL,
 "population" int NOT NULL,
 "metersAboveSeaLevel" float,
 "establishmentDate" date,
 "government_id" "government" NOT NULL,
 "standardOfLiving" "standardOfLiving" NOT NULL,
 "governor_id" int NOT NULL
);

ALTER TABLE "City" ADD FOREIGN KEY ("owner_id") REFERENCES "Users" ("id") ON DELETE CASCADE ;
ALTER TABLE "City" ADD FOREIGN KEY ("coordinates_id") REFERENCES "Coordinates" ("id") ON DELETE CASCADE ;
ALTER TABLE "City" ADD FOREIGN KEY ("governor_id") REFERENCES "Human" ("id") ON DELETE CASCADE ;


UPDATE "Users" SET name='kostya' WHERE id=2;
SELECT * FROM "Users" WHERE name='sonya';